executable('parity_dump', 'parity_dump.cpp', dependencies: [cobra_dep])
executable('inertial_parity_dump', 'inertial_parity_dump.cpp', dependencies: [cobra_dep])
executable('log_stats', 'log_stats.cpp', dependencies: [cobra_dep])
executable('lcm_log_player', 'lcm_log_player.cpp', dependencies: [cobra_dep])
executable('lcm_to_csv', 'lcm_to_csv.cpp', dependencies: [cobra_dep])
